-- 0002: 도메인 enum. packages/schemas/src/enums.ts 와 값이 1:1 로 대응한다.
-- enum 값을 바꿀 때는 반드시 양쪽을 같이 고친다.

CREATE TYPE user_role AS ENUM ('ADMIN', 'MEMBER');
CREATE TYPE gender AS ENUM ('MALE', 'FEMALE');

CREATE TYPE profile_status AS ENUM
  ('ACTIVE', 'MATCHING', 'PAUSED', 'INACTIVE', 'ARCHIVED');
CREATE TYPE profile_visibility AS ENUM ('LISTED', 'UNLISTED', 'PRIVATE');

CREATE TYPE job_category AS ENUM
  ('IT','FINANCE','PROFESSIONAL','PUBLIC','MARKETING','DESIGN','MEDICAL',
   'EDUCATION','SERVICE','BUSINESS','ART','OTHER');

CREATE TYPE region AS ENUM
  ('SEOUL','GYEONGGI','INCHEON','BUSAN','DAEGU','DAEJEON','GWANGJU','ULSAN',
   'SEJONG','GANGWON','CHUNGBUK','CHUNGNAM','JEONBUK','JEONNAM','GYEONGBUK',
   'GYEONGNAM','JEJU','OVERSEAS');

CREATE TYPE religion AS ENUM
  ('NONE','CHRISTIAN','CATHOLIC','BUDDHIST','WON_BUDDHIST','OTHER');

CREATE TYPE smoking_level AS ENUM ('NONE','OCCASIONAL','REGULAR');
CREATE TYPE drinking_level AS ENUM ('NONE','OCCASIONAL','SOCIAL','REGULAR');

CREATE TYPE match_request_status AS ENUM
  ('REQUESTED','ACCEPTED','REJECTED','CANCELED','INTRODUCED','CLOSED');

CREATE TYPE import_source AS ENUM ('KAKAO_SHARE','MANUAL_UPLOAD','SCREENSHOT','TEXT');
CREATE TYPE import_status AS ENUM
  ('RECEIVED','UPLOADING','ANALYZING','REVIEW_REQUIRED','READY','IMPORTED','FAILED');
CREATE TYPE import_asset_type AS ENUM ('IMAGE','FILE');
